### ISSUE TITLE
InvalidOperationException: .All() could not be translated

### ISSUE THREAD

**Issue by OculiViridi** [terryfkjc/EntityFrameworkCore.SqlServer.TemporalTable#2]
While trying to use the library to query my table I get this Exception:

> System.InvalidOperationException: The LINQ expression 'DbSet<Movimenti>()
    .All()' could not be translated. Either rewrite the query in a form that can be translated, or switch to client evaluation explicitly by inserting a call to 'AsEnumerable', 'AsAsyncEnumerable', 'ToList', or 'ToListAsync'. See https://go.microsoft.com/fwlink/?linkid=2101038 for more information.
	at Microsoft.EntityFrameworkCore.Query.QueryableMethodTranslatingExpressionVisitor.VisitMethodCall(MethodCallExpression methodCallExpression)
    at Microsoft.EntityFrameworkCore.Query.QueryCompilationContext.CreateQueryExecutor[TResult](Expression query)
    at Microsoft.EntityFrameworkCore.Storage.Database.CompileQuery[TResult](Expression query, Boolean async)
    at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.CompileQueryCore[TResult](IDatabase database, Expression query, IModel model, Boolean async)
    at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.<>c__DisplayClass12_0`1.<ExecuteAsync>b__0()
    at Microsoft.EntityFrameworkCore.Query.Internal.CompiledQueryCache.GetOrAddQuery[TResult](Object cacheKey, Func`1 compiler)
    at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.ExecuteAsync[TResult](Expression query, CancellationToken cancellationToken)
    at Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryProvider.ExecuteAsync[TResult](Expression expression, CancellationToken cancellationToken)
    at Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryable`1.GetAsyncEnumerator(CancellationToken cancellationToken)
    at System.Runtime.CompilerServices.ConfiguredCancelableAsyncEnumerable`1.GetAsyncEnumerator()
    at Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions.<ToListAsync>d__65`1.MoveNext()
    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
    at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()

I've made some tests but with no results. Am I missing something or doing something wrong?

#### Environment

EntityFrameworkCore.SqlServer.TemporalTable v1.2.4
.NET 5
EF Core 5
SQL Server 2017 v14.0.3370.1

#### Database

```sql
CREATE TABLE [reg].[Movements](
    [IdMovement] [bigint] IDENTITY(1,1) NOT NULL,
    [IdRegistry] [int] NOT NULL,
    -- Some other columns...
    [SysStartDate] [datetime2](7) GENERATED ALWAYS AS ROW START NOT NULL,
    [SysEndDate] [datetime2](7) GENERATED ALWAYS AS ROW END NOT NULL,
 CONSTRAINT [PK_Movements] PRIMARY KEY CLUSTERED 
(
    [IdMovement] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY],
    PERIOD FOR SYSTEM_TIME ([SysStartDate], [SysEndDate])
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
WITH
(
SYSTEM_VERSIONING = ON ( HISTORY_TABLE = [reg].[MovementsHistory] )
)
```

#### Entity Configuration

```csharp
public partial class MovementsConfiguration : IEntityTypeConfiguration<Movements>
{
    public void Configure(EntityTypeBuilder<Movimenti> entity)
    {
        entity.HasKey(e => e.IdMovements);

        // Some other settings for other columns...
    
        entity.HasTemporalTable(config =>
        {
            config.StartDateColumn("SysStartDate");
            config.EndDateColumn("SysEndDate");
            config.HistoryTable("MovementsHistory");
        });
    }
}
```

#### Query

```csharp
// Original query: FAILED
var movementsHistory = await Context.Movements
    .All()
    .Where(e => e.IdRegistry == request.IdRegistry && e.Id == request.IdMovement)
    .OrderByDescending(e => e.SysEndDate)
    .AsNoTrackingWithIdentityResolution()
    .ToListAsync(cancellationToken);

// Test 1: FAILED
var movementsHistory = await Context.Movements
    .Where(e => e.IdRegistry == request.IdRegistry && e.Id == request.IdMovement)
    .All()
    .OrderByDescending(e => e.SysEndDate)
    .AsNoTrackingWithIdentityResolution()
    .ToListAsync(cancellationToken);

// Test 2: FAILED
var movementsHistory = await Context.Movements
    .All()
    .ToListAsync(cancellationToken);

// Test 3: FAILED
var movementsHistory = await Context.Set<EntityFramework.Model.Movements>()
    .All()
    .ToListAsync(cancellationToken);
```

#### Notes

The `EntityFrameworkCore.SqlServer.TemporalTable` package is installed only on the EntityFramework project that contains entities and configurations. The Query is on a different project.

**Comment by terryfkjc** [comment]
Hi @OculiViridi,

You need to register your DbContext like the example below. 

```c#
 services.AddDbContext<UserDbContext>((provider, options) =>
 {
          options.UseInternalServiceProvider(provider);
          .....
 });

 services.AddEntityFrameworkSqlServer();
 services.RegisterTemporalTablesForDatabase();
```
Beside this, you may remove the `.All()` too.

Thanks.

**Comment by OculiViridi** [comment]
> Hi @OculiViridi,
> 
> You need to register your DbContext like the example below.
> 
> ```cs
>  services.AddDbContext<UserDbContext>((provider, options) =>
>  {
>           options.UseInternalServiceProvider(provider);
>           .....
>  });
> 
>  services.AddEntityFrameworkSqlServer();
>  services.RegisterTemporalTablesForDatabase();
> ```

Hi!
I thought that the `RegisterTemporalTablesForDatabase()` was only necessary for using Migrations, that I don't need. Anyway, I'm going to add it if it's needed!

> 
> Beside this, you may remove the `.All()` too.
> 
> Thanks.

What does this mean? If I want to query the table just like a "normal" one, so to get just the last (in time) valid recors, how can I prevent from getting all the cronological records?

**Comment by terryfkjc** [comment]
Sorry my bad, you need the `.All()` for the generated `FOR SYSTEM_TIME ALL`

Yes, your are right. You need the `UseInternalServiceProvider(...)` in order to let EF generate the temporary query for you.
This library will customize some internal services in EF core to support both migrations and temporary query.

EF core has no idea on how to translate `.All()`, `.AsOf(...)` .... (defined in `Microsoft.EntityFrameworkCore.DbSetExtensions)` into T-SQL.
